services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
 # container_name: <container_name> 
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
       # Uncomment if you need to include postgres database
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.godspeed

volumes:
  postgres_data:
